//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentPaymentNoticeSendLog
    {
        public int PaymentNoticeSendLogId { get; set; }
        public int Uid { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modifed { get; set; }
        public Nullable<int> RentPaymentId { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
        public virtual RentPayment RentPayment { get; set; }
    }
}
