//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.RentPayments = new HashSet<RentPayment>();
            this.RentPaymentNoticeSendLogs = new HashSet<RentPaymentNoticeSendLog>();
            this.UsersLogs = new HashSet<UsersLog>();
            this.UsersPasswords = new HashSet<UsersPassword>();
            this.UsersNotifications = new HashSet<UsersNotification>();
            this.UsersAccesses = new HashSet<UsersAccess>();
            this.UsersRoles = new HashSet<UsersRole>();
            this.UsersManagers = new HashSet<UsersManager>();
        }
    
        public int Uid { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modifed { get; set; }
        public bool Active { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<RentPayment> RentPayments { get; set; }
        public virtual ICollection<RentPaymentNoticeSendLog> RentPaymentNoticeSendLogs { get; set; }
        public virtual ICollection<UsersLog> UsersLogs { get; set; }
        public virtual ICollection<UsersPassword> UsersPasswords { get; set; }
        public virtual ICollection<UsersNotification> UsersNotifications { get; set; }
        public virtual ICollection<UsersAccess> UsersAccesses { get; set; }
        public virtual ICollection<UsersRole> UsersRoles { get; set; }
        public virtual ICollection<UsersManager> UsersManagers { get; set; }
    }
}
